package com.bivgroup.core.service.impl;

import com.bivgroup.core.service.interfaces.CoreManager;
import org.dbunit.DatabaseUnitException;
import org.dbunit.database.DatabaseDataSourceConnection;
import org.dbunit.database.IDatabaseConnection;
import org.dbunit.dataset.IDataSet;
import org.dbunit.dataset.xml.FlatXmlDataSetBuilder;
import org.dbunit.operation.DatabaseOperation;
import org.h2.jdbcx.JdbcDataSource;
import org.testng.annotations.AfterClass;
import org.testng.annotations.BeforeClass;

import java.io.File;
import java.net.MalformedURLException;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Arrays;
import java.util.List;

/**
 * Created by bush on 17.08.2016.
 */
public abstract class AbstractTest {
    String url = "";
    Statement statement;
    public JdbcDataSource dataSource;
    public CoreManager coreFacade;


    private void executeSql(List<String> list_statement) throws SQLException {
        for (String statementsql : list_statement) {
            try {
                statement.execute(statementsql);
            } catch (SQLException sqle) {
                System.out.println("Table not found, not dropping, not create");
            }
        }
    }

    /**
     * Инициируем соединение и заполняем данными
     */
    @BeforeClass
    public void setUp() throws SQLException, DatabaseUnitException, MalformedURLException {

        this.url = "jdbc:h2:mem:test";
        dataSource = new JdbcDataSource();
        dataSource.setURL(this.url);
        IDatabaseConnection con = new DatabaseDataSourceConnection(dataSource);
        statement = con.getConnection().createStatement();

        List<String> list_drop = Arrays.asList(
                "DROP TABLE SM_OBJSTATE",
                "DROP TABLE SM_OBJSTATEH",
                "DROP TABLE CORE_PROJECT",
                "DROP TABLE CORE_SETTING",
                "DROP TABLE CORE_USRSETTING",
                "DROP TABLE CORE_USER",
                "DROP TABLE CORE_USERGROUP",
                "DROP TABLE CORE_CORE_USERINGROUP",
                "DROP TABLE CORE_USERACCOUNT",
                "DROP TABLE DEP_DEPARTMENT",
                "DROP TABLE DEP_DEPPARENT",
                "DROP TABLE DEP_DEPTLEVEL",
                "DROP TABLE DEP_EMPLOYEE",
                "DROP TABLE DEP_ADDRESS",
                "DROP TABLE CORE_KLADROBJ",
                "DROP TABLE CORE_KLADRSTREET",
                "DROP TABLE REF_EXCHANGE",
                "DROP TABLE REF_EXCHANGETYPE",
                "DROP TABLE REF_CURRENCY",
                "DROP TABLE REF_CURRENCYPAIR",
                "DROP TABLE CORE_USERROLE",
                "DROP TABLE CORE_ROLEACCOUNT",
                "DROP TABLE CORE_RIGHT",
                "DROP TABLE CORE_RIGHTACCOUNT",
                "DROP TABLE CORE_RIGHTUSRGROUP",
                "DROP TABLE CORE_RIGHTUSERROLE",
                "DROP TABLE CORE_RIGHTDEPT",
                "DROP TABLE CORE_RIGHTFILTER",
                "DROP TABLE CORE_RFVALUE",
                "DROP TABLE CORE_PARTICIPANT",
                "DROP TABLE CORE_MASK",
                "DROP TABLE REF_REFITEM",
                "DROP TABLE REF_REFERENCE",
                "DROP TABLE CORE_USERCERT",
                "DROP TABLE CORE_MASSOPERTYPE",
                "DROP TABLE CORE_MASSOPER"
        );

        List<String> list_create = Arrays.asList(
                "CREATE TABLE SM_OBJSTATE ( ID NUMERIC(19,0) NOT NULL,OBJID   NUMERIC(19,0) NOT NULL, STATEID NUMERIC(19,0) NOT NULL ,STATENAME VARCHAR(255)  NOT NULL ,TYPEID  NUMERIC(19,0) NOT NULL ,TYPENAME VARCHAR(255)  NOT NULL ,STARTDATE FLOAT(38)     NOT NULL ,USERNAME VARCHAR(255)  NOT NULL)",
                "CREATE TABLE SM_OBJSTATEH (ID NUMERIC(19,0) NOT NULL,OBJID  NUMERIC(19,0) NOT NULL,STATEID NUMERIC(19,0) NOT NULL, STATENAME VARCHAR(255)  NOT NULL, TYPEID  NUMERIC(19,0) NOT NULL,TYPENAME VARCHAR(255)  NOT NULL,STARTDATE FLOAT(38)     NOT NULL,USERNAME VARCHAR(255)  NOT NULL,COMMENTARY CLOB  NULL)",


                "CREATE TABLE CORE_PROJECT (PROJECTID NUMERIC(19,0) NOT NULL, METADATAURL  VARCHAR(255)  NOT NULL, PROJECTSYSNAME VARCHAR(255), PROJECTNAME VARCHAR(255),MAINMENUID NUMERIC(19,0), DEFAULTLANGUAGEID NUMERIC(19,0), PROJECTDESCR VARCHAR(255), USEASDEFAULT VARCHAR(255), USERMETADATAURL VARCHAR(255))",

                "CREATE TABLE CORE_SETTING (ID NUMERIC(19,0) NOT NULL, SETTINGSYSNAME VARCHAR(255)  NOT NULL , SETTINGVALUE VARCHAR(255)  NOT NULL )",
                "CREATE TABLE CORE_USRSETTING (USRSETTINGID NUMERIC(19,0) NOT NULL, USERACCOUNTID NUMERIC(19,0) NOT NULL,USRSETTINGSYSNAME VARCHAR(255)  NOT NULL , USRSETTINGNAME VARCHAR(255)  NOT NULL , USRSETTINGVALUE VARCHAR(255)  NOT NULL )",

                "CREATE TABLE CORE_USER ( USERID NUMERIC(19,0) NOT NULL, PARTICIPANTID NUMERIC(19,0), OBJECTID NUMERIC(19,0), OBJECTTYPE NUMERIC(19,0), STATUS VARCHAR(255), BLOCKIFINACTIVE NUMERIC(19,0))",
                "CREATE TABLE CORE_USERACCOUNT (USERACCOUNTID NUMERIC(19,0), USERID NUMERIC(19,0) NOT NULL, LOGIN VARCHAR(255), STATUS VARCHAR(255), ISCONCURRENT NUMERIC(19,0), ROLE VARCHAR(255), PASSWORD VARCHAR(255),CREATIONDATE FLOAT , PREFLANGUAGE VARCHAR(255), AUTHMETHOD VARCHAR(255), DESCRIPTION VARCHAR(255), FAILEDLOGINS NUMERIC(19,0),PWDEXPDATE FLOAT,LASTLOGOUTEVENT VARCHAR(255),LASTLOGINEVENT FLOAT,LOGOUTDUETO VARCHAR(255),EXTERNALID NUMERIC(19,0))",


                "CREATE TABLE DEP_DEPARTMENT(DEPARTMENTID NUMERIC(19,0) NOT NULL,PARENTDEPARTMENT NUMERIC(19,0), DEPTLEVEL NUMERIC(19,0),DEPTCODE NUMERIC(19,0),DEPTSHORTNAME VARCHAR(255),DEPTFULLNAME VARCHAR(255),MANAGER NUMERIC(19,0), PARAM1 VARCHAR(255),PARAM2 VARCHAR(255),PARAM3 VARCHAR(255)," +
                        "DEPUSELINK NUMERIC(19,0),DEPLINKID NUMERIC(19,0), DEPPHONE VARCHAR(255), DEPMAIL VARCHAR(255), DEPPARENTTZ NUMERIC(19,0),DEPTZNAME VARCHAR(255),DEPTZDIFF VARCHAR(255),DEPTZCHANGE VARCHAR(255)) ",

                "CREATE TABLE DEP_DEPTLEVEL(DEPTLEVELID NUMERIC(19,0) NOT NULL, LEVELWEIGHT NUMERIC(19,0) ,LEVELSYSNAME VARCHAR(255),LEVELNAME VARCHAR(255), DESCRIPTION VARCHAR(255))",
                "CREATE TABLE DEP_EMPLOYEE(EMPLOYEEID NUMERIC(19,0),LASTNAME VARCHAR(255),FIRSTNAME VARCHAR(255),MIDDLENAME VARCHAR(255),PARTICIPANTID NUMERIC(19,0), CODE VARCHAR(255), MANAGERID NUMERIC(19,0) , EMPLOYEENAME VARCHAR(255), POSITION VARCHAR(255), DEPARTMENTID NUMERIC(19,0), STARTWORKDATE FLOAT, ENDWORKDATE FLOAT, STATUS VARCHAR(255),MANAGER NUMERIC(19,0),PHONE1 VARCHAR(255),PHONE2 VARCHAR(255),EMAIL VARCHAR(255))",

                "CREATE TABLE DEP_ADDRESS(ADDRID NUMERIC(19,0) NOT NULL,OBJECTID NUMERIC(19,0) NOT NULL, OBJECTTYPE NUMERIC(19,0) NOT NULL, POSTALCODE VARCHAR(255),FLAT VARCHAR(255),HOUSE VARCHAR(255),BUILDING VARCHAR(255),HOUSING VARCHAR(255),FIRST_LEVEL NUMERIC(19,0),SECOND_LEVEL NUMERIC(19,0),THIRD_LEVEL NUMERIC(19,0),FOURTH_LEVEL NUMERIC(19,0),FIFTH_LEVEL NUMERIC(19,0))",
                "CREATE TABLE CORE_KLADROBJ(ID NUMERIC(19,0) NOT NULL, CODE NUMERIC(19,0), FULLNAME VARCHAR(255), SHORTNAME VARCHAR(255))",
                "CREATE TABLE CORE_KLADRSTREET(ID NUMERIC(19,0) NOT NULL, CODE NUMERIC(19,0), FULLNAME VARCHAR(255), SHORTNAME VARCHAR(255))",

                "CREATE TABLE REF_EXCHANGE(EXCHANGEID NUMERIC(19,0), UNITS NUMERIC(19,0), COURSEVALUE NUMERIC(19,4), EXCHANGETYPEID NUMERIC(19,0), CURRENCYPAIRID NUMERIC(19,0), COURSEDATE FLOAT )",
                "CREATE TABLE REF_EXCHANGETYPE(EXCHANGETYPEID NUMERIC(19,0),COURSETYPENAME VARCHAR(255))",
                "CREATE TABLE REF_CURRENCY(CURRENCYID NUMERIC(19,0), ALPHACODE VARCHAR(255),CURRENCYNAME VARCHAR(255),NUMERICCODE NUMERIC(5,0), NAMEWORDFORMID NUMERIC(19,0), MINORUNIT NUMERIC(19,0), MINORUNITFORMID NUMERIC(19,0), FRACTIONALPART NUMERIC(19,0), ISONUMBER NUMERIC(5,0))",
                "CREATE TABLE REF_CURRENCYPAIR(CURRENCYPAIRID NUMERIC(19,0), BASECURRENCYID NUMERIC(19,0), QUOTEDCURRENCYID NUMERIC(19,0), STATUS NUMERIC(19,0), STARTDATE FLOAT , ENDDATE FLOAT )",

                "CREATE TABLE CORE_USERROLE( ROLEID NUMERIC(19,0), ROLESYSNAME VARCHAR(255), ROLENAME VARCHAR(255), DESCRIPTION VARCHAR(255),FROMDATE FLOAT, TODATE FLOAT)",
                "CREATE TABLE CORE_ROLEACCOUNT(ROLEACCOUNTID NUMERIC(19,0),ROLEID NUMERIC(19,0), TODATE FLOAT , USERACCOUNTID NUMERIC(19,0))",

                "CREATE TABLE CORE_RIGHT(RIGHTID NUMERIC(19,0), RIGHTSYSNAME VARCHAR(255))",
                "CREATE TABLE CORE_RIGHTACCOUNT(RIGHTACCOUNTID NUMERIC(19,0),USERACCOUNTID NUMERIC(19,0),RIGHTID NUMERIC(19,0), ISEXCEPTION NUMERIC(19,0), EXCEPTIONMODE NUMERIC(19,0), ACCESSMODE VARCHAR(255), STARTDATE FLOAT, ENDDATE FLOAT)",
                "CREATE TABLE CORE_RIGHTDEPT(RIGHTDEPTID NUMERIC(19,0),DEPARTMENTID NUMERIC(19,0),RIGHTID NUMERIC(19,0), ISEXCEPTION NUMERIC(19,0), EXCEPTIONMODE NUMERIC(19,0),ACCESSMODE VARCHAR(255), STARTDATE FLOAT, ENDDATE FLOAT)",
                "CREATE TABLE CORE_RIGHTFILTER(RIGHTFILTERID NUMERIC(19,0),SYSNAME VARCHAR(255),  OPERATION VARCHAR(255), ANYVALUE NUMERIC(19,0) ,RELATIONID NUMERIC(19,0), RELATIONTYPE VARCHAR(255))",
                "CREATE TABLE CORE_RFVALUE(RIGHTFILTERID NUMERIC(19,0),VALUE VARCHAR(255),VKEY VARCHAR(255))",
                "CREATE TABLE CORE_RIGHTUSERROLE(RIGHTUSERROLEID NUMERIC(19,0), ROLEID NUMERIC(19,0), RIGHTID NUMERIC(19,0), ISEXCEPTION NUMERIC(19,0), EXCEPTIONMODE NUMERIC(19,0), ACCESSMODE VARCHAR(255),  STARTDATE FLOAT, ENDDATE FLOAT)",
                "CREATE TABLE CORE_RIGHTUSRGROUP(RIGHTUSRGROUPID NUMERIC(19,0), RIGHTID NUMERIC(19,0),USERGROUPID  NUMERIC(19,0) , ISEXCEPTION NUMERIC(19,0), EXCEPTIONMODE NUMERIC(19,0), ACCESSMODE VARCHAR(255),  STARTDATE FLOAT, ENDDATE FLOAT)",
                "CREATE TABLE CORE_USERGROUP(USERGROUPID NUMERIC(19,0), GROUPID NUMERIC(19,0),RELATIONSHIP VARCHAR(255), USERID NUMERIC(19,0) , GROUPNAME VARCHAR(255))",
                "CREATE TABLE CORE_USERINGROUP(USERGROUPID NUMERIC(19,0), GROUPID NUMERIC(19,0), RELATIONSHIP VARCHAR(255), USERID NUMERIC(19,0))",
                "CREATE TABLE DEP_DEPPARENT( DEPPARENTID NUMERIC(19,0),DEPARTMENTID NUMERIC(19,0), PARENTDEPARTMENT NUMERIC(19,0),RELATIONSHIP VARCHAR(255) )",

                "CREATE TABLE CORE_PARTICIPANT(PARTICIPANTID NUMERIC(19,0), PARTICIPANTNAME VARCHAR(255) )",

                "CREATE TABLE CORE_MASK(MASKID NUMERIC(19,0), SYSTEMBRIEF VARCHAR(255), MASK VARCHAR(255), CRITERION VARCHAR(255), DESCRIPTION VARCHAR(255) )",

                "CREATE TABLE REF_REFITEM(REFITEMID NUMERIC(19,0), REFERENCEID NUMERIC(19,0),  CODE NUMERIC(19,0),SHORTVALUE VARCHAR(255), FULLVALUE VARCHAR(255))",
                "CREATE TABLE REF_REFERENCE(REFERENCEID NUMERIC(19,0),REFSYSNAME VARCHAR(255))",

                "CREATE TABLE CORE_USERCERT(SIGNERID NUMERIC(19,0),USERACCOUNTID NUMERIC(19,0),DATETO FLOAT)",

                "CREATE TABLE CORE_MASSOPERTYPE(MASSOPERTYPEID NUMERIC(19,0), OPERSYSNAME VARCHAR(255), OPERNAME VARCHAR(255))",
                "CREATE TABLE CORE_MASSOPER(MASSOPERID NUMERIC(19,0), OPERNAME VARCHAR(255),DETAIL VARCHAR(255), OPERSTATUS VARCHAR(255), OPERSTARTDATE FLOAT, CURRENTPERCENT NUMERIC(19,0), OPERSTARTER VARCHAR(255), MASSOPERTYPEID NUMERIC(19,0))"
        );

        executeSql(list_drop);
        executeSql(list_create);


        IDataSet dataSet = new FlatXmlDataSetBuilder().build(new File("src/test/resources/com/bivgroup/db/TestDataset.xml"));
        DatabaseOperation.CLEAN_INSERT.execute(con, dataSet);


        coreFacade = new CoreManagerImpl(dataSource);

    }

    @AfterClass
    public void setDownt() throws SQLException {
        statement.close();
        //connection.close();
    }
}
