//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.15 at 03:12:33 PM GMT+03:00 
//


package com.bivgroup.core.aspect.bean;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AspectsOnModule complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AspectsOnModule"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="nameModule" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="aspectsOnEntity" type="{http://bivgroup.aspect.com/}AspectsOnEntity" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AspectsOnModule", propOrder = {
    "nameModule",
    "aspectsOnEntity"
})
public class AspectsOnModule {

    @XmlElement(required = true)
    protected String nameModule;
    @XmlElement(nillable = true)
    protected List<AspectsOnEntity> aspectsOnEntity;

    /**
     * Gets the value of the nameModule property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNameModule() {
        return nameModule;
    }

    /**
     * Sets the value of the nameModule property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNameModule(String value) {
        this.nameModule = value;
    }

    /**
     * Gets the value of the aspectsOnEntity property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the aspectsOnEntity property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAspectsOnEntity().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AspectsOnEntity }
     * 
     * 
     */
    public List<AspectsOnEntity> getAspectsOnEntity() {
        if (aspectsOnEntity == null) {
            aspectsOnEntity = new ArrayList<AspectsOnEntity>();
        }
        return this.aspectsOnEntity;
    }

}
