//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.15 at 03:12:33 PM GMT+03:00 
//


package com.bivgroup.core.aspect.bean;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.bivgroup.core.aspect.bean package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _AspectsOnModule_QNAME = new QName("http://bivgroup.aspect.com/", "aspectsOnModule");
    private final static QName _AspectsOnEntity_QNAME = new QName("http://bivgroup.aspect.com/", "aspectsOnEntity");
    private final static QName _AspectCfg_QNAME = new QName("http://bivgroup.aspect.com/", "aspectCfg");
    private final static QName _Field_QNAME = new QName("http://bivgroup.aspect.com/", "field");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.bivgroup.core.aspect.bean
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Aspects }
     * 
     */
    public Aspects createAspects() {
        return new Aspects();
    }

    /**
     * Create an instance of {@link AspectsOnModule }
     * 
     */
    public AspectsOnModule createAspectsOnModule() {
        return new AspectsOnModule();
    }

    /**
     * Create an instance of {@link AspectsOnEntity }
     * 
     */
    public AspectsOnEntity createAspectsOnEntity() {
        return new AspectsOnEntity();
    }

    /**
     * Create an instance of {@link AspectCfg }
     * 
     */
    public AspectCfg createAspectCfg() {
        return new AspectCfg();
    }

    /**
     * Create an instance of {@link Field }
     * 
     */
    public Field createField() {
        return new Field();
    }

    /**
     * Create an instance of {@link StateAspect }
     * 
     */
    public StateAspect createStateAspect() {
        return new StateAspect();
    }

    /**
     * Create an instance of {@link BinaryFile }
     * 
     */
    public BinaryFile createBinaryFile() {
        return new BinaryFile();
    }

    /**
     * Create an instance of {@link VersionAspect }
     * 
     */
    public VersionAspect createVersionAspect() {
        return new VersionAspect();
    }

    /**
     * Create an instance of {@link AuthAspect }
     * 
     */
    public AuthAspect createAuthAspect() {
        return new AuthAspect();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AspectsOnModule }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://bivgroup.aspect.com/", name = "aspectsOnModule")
    public JAXBElement<AspectsOnModule> createAspectsOnModule(AspectsOnModule value) {
        return new JAXBElement<AspectsOnModule>(_AspectsOnModule_QNAME, AspectsOnModule.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AspectsOnEntity }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://bivgroup.aspect.com/", name = "aspectsOnEntity")
    public JAXBElement<AspectsOnEntity> createAspectsOnEntity(AspectsOnEntity value) {
        return new JAXBElement<AspectsOnEntity>(_AspectsOnEntity_QNAME, AspectsOnEntity.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AspectCfg }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://bivgroup.aspect.com/", name = "aspectCfg")
    public JAXBElement<AspectCfg> createAspectCfg(AspectCfg value) {
        return new JAXBElement<AspectCfg>(_AspectCfg_QNAME, AspectCfg.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Field }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://bivgroup.aspect.com/", name = "field")
    public JAXBElement<Field> createField(Field value) {
        return new JAXBElement<Field>(_Field_QNAME, Field.class, null, value);
    }

}
