//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.15 at 03:12:33 PM GMT+03:00 
//


package com.bivgroup.core.aspect.bean;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for StateAspect complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="StateAspect"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://bivgroup.aspect.com/}Aspect"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="typeSysName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="startStateName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="idFieldName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="productPrefix" type="{http://www.w3.org/2001/XMLSchema}string" default="INS" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "StateAspect", propOrder = {
    "typeSysName",
    "startStateName",
    "idFieldName"
})
public class StateAspect
    extends Aspect
{

    @XmlElement(required = true)
    protected String typeSysName;
    @XmlElement(required = true)
    protected String startStateName;
    @XmlElement(required = true)
    protected String idFieldName;
    @XmlAttribute(name = "productPrefix")
    protected String productPrefix;

    /**
     * Gets the value of the typeSysName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTypeSysName() {
        return typeSysName;
    }

    /**
     * Sets the value of the typeSysName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTypeSysName(String value) {
        this.typeSysName = value;
    }

    /**
     * Gets the value of the startStateName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStartStateName() {
        return startStateName;
    }

    /**
     * Sets the value of the startStateName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStartStateName(String value) {
        this.startStateName = value;
    }

    /**
     * Gets the value of the idFieldName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdFieldName() {
        return idFieldName;
    }

    /**
     * Sets the value of the idFieldName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdFieldName(String value) {
        this.idFieldName = value;
    }

    /**
     * Gets the value of the productPrefix property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductPrefix() {
        if (productPrefix == null) {
            return "INS";
        } else {
            return productPrefix;
        }
    }

    /**
     * Sets the value of the productPrefix property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductPrefix(String value) {
        this.productPrefix = value;
    }

}
